# Generated by Django 5.1.7 on 2025-05-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='documentation',
            field=models.FileField(blank=True, null=True, upload_to='product_docs/', verbose_name='Документация'),
        ),
    ]
