# Generated by Django 5.1.7 on 2025-05-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_product_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт производителя'),
        ),
    ]
