# Generated by Django 5.1.7 on 2025-06-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_apartment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к доставке'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_house',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Улица'),
        ),
    ]
