# Generated by Django 5.1.7 on 2025-06-23 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('assembling', 'В сборке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='PEExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('exam_date', models.DateTimeField(verbose_name='Дата проведения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam_images/', verbose_name='Изображение задания')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('users', models.ManyToManyField(related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
