@startuml
entity "Пользователь" as User {
    id
    ---
    email
    имя_пользователя
    пароль
    фото_профиля
}

entity "Категория" as Category {
    id
    ---
    название
}

entity "Товар" as Product {
    id
    category_id
    ---
    название
    описание
    цена
    количество
    изображение
}

entity "Заказ" as Order {
    id
    user_id
    ---
    статус
    общая_цена
    дата_создания
}

entity "Товары в заказе" as OrderItem {
    id
    order_id
    product_id
    ---
    количество
    цена
}

entity "Отзыв" as Review {
    id
    user_id
    product_id
    ---
    рейтинг
    комментарий
    дата_создания
}

entity "Избранное" as Wishlist {
    id
    user_id
    product_id
}

' Определение связей (инфологический уровень)
User ||--o{ Order : "оформляет" 
Order ||--o{ OrderItem : "содержит"
Product ||--o{ OrderItem : "включён в"

User ||--o{ Review : "пишет"
Product ||--o{ Review : "имеет"

User ||--o{ Wishlist : "сохраняет"
Product ||--o{ Wishlist : "в избранном"

Category ||--o{ Product : "включает"
@enduml
